---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WangChen.
--- DateTime: 2022/8/1 9:25
---

local format    = string.format
local gsub      = string.gsub
local tonumber  = tonumber
local toString  = tostring

local QUERY_SQL = [[ SELECT %s FROM rate_limit_path_config WHERE tenant_id = '%s' AND route_id = '%s' AND service_id = '%s' ]]

local function page_rate_limit_path_configs_query_sql(tenant_id, route_id, service_id, page, size, search)
    local page_number = tonumber(page)
    local size_number = tonumber(size)
    if not page_number then
        page_number = 1
    end
    if not size_number then
        size_number = 10
    end
    if page_number <= 1 then
        page_number = 1
    end
    if size_number > 100 then
        size_number = 100
    end
    local query_sql = format(QUERY_SQL, "*", tenant_id, route_id, service_id)
    local count_query_sql = format(QUERY_SQL, "COUNT(*)", tenant_id, route_id, service_id)
    if search then
        query_sql = query_sql .. gsub("AND path LIKE '%{}%' ", "{}", search)
        count_query_sql = count_query_sql .. gsub("AND path LIKE '%{}%' ", "{}", search)
    end
    query_sql = query_sql .. " LIMIT " .. toString(size_number) .. " OFFSET " .. toString(page_number - 1)
    count_query_sql = count_query_sql
    return page_number, size_number, query_sql, count_query_sql
end


return {
    page_rate_limit_path_configs_query_sql = page_rate_limit_path_configs_query_sql
}